### ISSUE TITLE
Min Max months start at 0 for January

### ISSUE THREAD

**Issue by anthonymidili** [veracross/pickadate-rails#17]
`$('.datepicker').pickadate({
  min: [2015,3,20],
  max: [2015,7,14]
})`
is actually **min: [2015, April, 20], max: [2015, August, 14]**.

**Comment by sixfeetover** [comment]
If you have tickets for pickadate, please post them on https://github.com/amsul/pickadate.js. This repo is just a Rails wrapper for pickadate, not the library itself.
