### ISSUE TITLE
Year dropdown looks funky

### ISSUE THREAD

**Issue by mrmanishs** [veracross/pickadate-rails#18]
I installed the gem and implemented it on a text field, the rails dropdown does not look the same as the example on the site. Here is what I am seeing.

<img width="632" alt="screen shot 2016-08-13 at 1 45 23 pm" src="https://cloud.githubusercontent.com/assets/124528/17644713/343a3138-615c-11e6-8dcb-394f1bbcd265.png">

**Comment by sixfeetover** [comment]
Looks like you just have some conflicting styles in your app, or there's a bug in pickadate itself. This gem just wraps pickadate in order to make it easier to include in Rails. If you have issues or questions, try the [pickadate](https://github.com/amsul/pickadate.js) repository.
